### ISSUE TITLE
Targets

### ISSUE THREAD

**Issue by Alfriadox** [Alfriadox/wright-lang#35]
This is pretty far in the future, but I'll leave some platforms I'm considering targeting here, to look back at for reference later:
- C
- JVM
- LLVM
- Cretonne (If it still exists.)
- Rust (maybe?)
- MIPS (or some subset)
- Brainfuck (maybe?)
- WASM (maybe?)

**Comment by Alfriadox** [comment]
I think Cretonne got renamed to Cranelift and moved to https://github.com/bytecodealliance/wasmtime/tree/master/cranelift

**Comment by io12** [comment]
There are LLVM backends for [JVM](https://github.com/davidar/lljvm), [C](https://github.com/JuliaComputing/llvm-cbe), MIPS, and [WASM](https://emscripten.org/) so LLVM gets us all of those for free. (JVM probably requires more work though)

**Comment by Alfriadox** [comment]
yeah I agree with that, but there may be some optimizations/advantages to compiling to some of these targets directly, rather than through LLVM. Targetting LLVM is definitely a goal of mine though. I just balk slightly at the amount of work it might involve.

**Comment by io12** [comment]
I wrote a broken LLVM frontend in C once. LLVM's C/C++ library (and hopefully the rust bindings) has a builder API for building an LLVM module with function calls. Mutable variables need stack space allocated with an `alloca` instruction and control flow statements need to be translated to raw jumps/branches, but other than that, it's not *terrible*.
